# Generated by Django 3.0.1 on 2024-03-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='wishitem',
            name='size',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
