# Generated by Django 3.0.1 on 2024-03-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_auto_20240326_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishitem',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
