# Generated by Django 3.0.1 on 2024-05-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_auto_20240326_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
