# Generated by Django 3.0.1 on 2024-05-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0005_remove_wishitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishitem',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
