# Generated by Django 3.0.1 on 2024-03-18 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_featured_image'),
    ]

    operations = [
    ]
