# Generated by Django 3.0.1 on 2024-03-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20240319_1603'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='post',
        #     name='featured_image',
        #     field=models.ImageField(blank=True, null=True, upload_to=''),
        # ),
    ]
