# Generated by Django 3.0.1 on 2024-03-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20240321_1706'),
    ]

