# Generated by Django 3.0.1 on 2024-03-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_featured_image'),
    ]

    operations = [
    ]
