# Generated by Django 3.0.1 on 2024-03-24 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishItem',
        ),
    ]
